apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt-contact-ui
  labels:
    app: stt-contact-ui
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stt-contact-ui
      version: v1
  template:
    metadata:
      labels:
        app: stt-contact-ui
        version: v1
    spec:
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: tmp-volume
        emptyDir: {}
      containers:
      - name: stt-contact-ui
        image: ghcr.io/staillanibm/stt-contact-ui:v1.1.0
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: VITE_APP_URL
          value: "https://contact-ui-contact.apps.itz-zmhpfy.infra01-lb.fra02.techzone.ibm.com"
        - name: VITE_KEYCLOAK_AUTHORITY
          value: "https://keycloak.staging.e-auth.cloud/realms/sttlab"
        - name: VITE_KEYCLOAK_CLIENT_ID
          value: "47283985-2eed-4484-bc28-dc03f0e446fe"
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: stt-contact-ui
  labels:
    app: stt-contact-ui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: stt-contact-ui

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stt-contact-ui-config
data:
  app.config.js: |
    window.APP_CONFIG = {
      KEYCLOAK_AUTHORITY: "${VITE_KEYCLOAK_AUTHORITY}",
      KEYCLOAK_CLIENT_ID: "${VITE_KEYCLOAK_CLIENT_ID}",
      APP_URL: "${VITE_APP_URL}"
    };
